llm:
  provider: google
  config:
    model: gemini-pro
    temperature: 0.1
    top_p: 1
    stream: false

embedder:
  provider: google
  config:
    model: 'models/embedding-001'
    task_type: "retrieval_document"
    title: "Embeddings for Embedchain"
